# Generated by Django 2.2 on 2021-06-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_url', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=250)),
            ],
        ),
    ]
