# Generated by Django 3.0 on 2021-06-29 20:27

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assistleadapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('data', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
